version: '3.8'

services:
  backend-web:
    container_name: 'backend.web'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '15011:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-php
      - backend-mysql
  backend-php:
    container_name: 'backend.php'
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    #command: php artisan serve --port 3000

  backend-mysql:
    container_name: 'backend.mysql'
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: smRbRoot
      MYSQL_DATABASE: flutter_backend
      MYSQL_USER: fl_backend_user
      MYSQL_PASSWORD: sl_P@ss
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initial_table:/docker-entrypoint-initdb.d


  backend-myadmin:
    container_name: 'backend.myadmin'
    depends_on:
      - backend-mysql
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: backend-mysql
    restart: always
    ports:
      - "15021:80"

